development:
  adapter: postgresql
  encoding: unicode
  database: servicehub_dev
  pool: 5
  username: localapp
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: servicehub_test
  pool: 5
  username: localapp
  password: password1